-- Auto-generated seed matching ingest.py chunking rules, run once at
-- first container boot (docker-entrypoint-initdb.d only runs against an
-- empty data directory), so unlike running ingest.py by hand this cannot
-- accidentally duplicate rows on container restart.

INSERT INTO documents (content) VALUES ('Regular physical activity is essential for maintaining overall health and well-being. It helps reduce the risk of chronic diseases such as heart disease, diabetes, and obesity.
Adults should engage in at least 150 minutes of moderate intensity aerobic activity or 75 minutes of vigorous intensity activity per week for optimal health benefits.
Walking and jogging are accessible forms of aerobic exercise that improve cardiovascular endurance and support weight management.
Strength training exercises such as resistance training and bodyweight exercises help maintain muscle mass and bone density.
Flexibility exercises such as stretching improve joint mobility and reduce the risk of injury during physical activity.
Physical activity contributes positively to mental health by reducing symptoms of anxiety, depression, and stress.
Regular exercise improves sleep quality and helps regulate circadian rhythms.
Maintaining an active lifestyle is associated with increased life expectancy and better quality of life.
Children and adolescents should engage in at least 60 minutes of moderate to vigorous physical activity daily.
Sedentary behavior, such as prolonged sitting, is associated with increased health risks and should be minimized.
Muscle strengthening activities should be performed at least two days per week.
Balance and coordination exercises are especially important for older adults to prevent falls.
Hydration is important during physical activity to maintain performance and prevent dehydration.
Nutrition plays a key role in supporting physical activity, including adequate intake of protein, carbohydrates, and healthy fats.
Warm up activities prepare the body for exercise by increasing heart rate and blood circulation.
Cool down exercises help gradually lower heart rate and prevent dizziness after intense activity.
Regular physical activity supports immune system function and overall resilience.
Moderate intensity exercise includes activities such as brisk walking, cycling, and recreational sports.
Vigorous intensity exercise includes running, high intensity interval training, and competitive sports.
Consistency in physical activity is more important than intensity for long term health outcomes.');
INSERT INTO documents (content) VALUES ('Push-up is a bodyweight exercise that targets chest, shoulders and triceps. Keep your body straight and lower until your chest nearly touches the floor.');
INSERT INTO documents (content) VALUES ('Squat is a compound lower body exercise that targets quadriceps, hamstrings and glutes. Keep your back straight and knees aligned with toes.');
INSERT INTO documents (content) VALUES ('Plank is a core stability exercise that strengthens abdominal muscles and improves posture.');
INSERT INTO documents (content) VALUES ('Deadlift is a strength exercise that targets back, glutes and hamstrings using a barbell or dumbbells.');
INSERT INTO documents (content) VALUES ('Lunges improve balance and strengthen the legs by stepping forward and lowering the body.');
INSERT INTO documents (content) VALUES ('Bench press is a strength exercise for chest and triceps performed with a barbell or dumbbells.');
INSERT INTO documents (content) VALUES ('Shoulder press targets the deltoid muscles and improves upper body strength.');
INSERT INTO documents (content) VALUES ('Bicep curl isolates the biceps and improves arm strength.');
INSERT INTO documents (content) VALUES ('Tricep dips target the triceps using body weight and a stable surface.');
INSERT INTO documents (content) VALUES ('Pull-up is an upper body exercise that strengthens the back and arms.');
INSERT INTO documents (content) VALUES ('Leg press is a machine exercise that targets the quadriceps and glutes.');
INSERT INTO documents (content) VALUES ('Calf raises strengthen the calf muscles and improve ankle stability.');
INSERT INTO documents (content) VALUES ('Russian twists target the obliques and improve core rotation strength.');
INSERT INTO documents (content) VALUES ('Mountain climbers are a dynamic exercise that improves cardio and core strength.');
INSERT INTO documents (content) VALUES ('Burpees are a full body exercise that combines strength and cardio training.');
INSERT INTO documents (content) VALUES ('Jump rope improves coordination, agility and cardiovascular fitness.');
INSERT INTO documents (content) VALUES ('Hip thrust targets the glutes and improves lower body power.');
INSERT INTO documents (content) VALUES ('Lat pulldown strengthens the upper back and lats using a cable machine.');
INSERT INTO documents (content) VALUES ('Leg curl isolates the hamstrings and improves knee stability.');
INSERT INTO documents (content) VALUES ('Leg extension targets the quadriceps using a machine.');
INSERT INTO documents (content) VALUES ('Chest fly isolates the chest muscles using dumbbells or a machine.');
INSERT INTO documents (content) VALUES ('Arnold press strengthens the shoulders and improves stability.');
INSERT INTO documents (content) VALUES ('Hammer curl targets the brachialis and forearms.');
INSERT INTO documents (content) VALUES ('Skull crushers strengthen the triceps using a barbell.');
INSERT INTO documents (content) VALUES ('Side plank strengthens the obliques and improves core stability.');
INSERT INTO documents (content) VALUES ('Bicycle crunch targets the abdominal muscles and improves endurance.');
INSERT INTO documents (content) VALUES ('Step-ups strengthen the legs and improve balance.');
INSERT INTO documents (content) VALUES ('Wall sit improves endurance in the quadriceps.');
INSERT INTO documents (content) VALUES ('Glute bridge strengthens the glutes and lower back.');
INSERT INTO documents (content) VALUES ('Superman exercise strengthens the lower back muscles.');
INSERT INTO documents (content) VALUES ('Face pull improves shoulder health and posture.');
INSERT INTO documents (content) VALUES ('Farmer''s walk improves grip strength and core stability.');
INSERT INTO documents (content) VALUES ('Kettlebell swing improves power and cardiovascular fitness.');
INSERT INTO documents (content) VALUES ('Box jumps improve explosive leg power.');
INSERT INTO documents (content) VALUES ('High knees improve cardio and coordination.');
INSERT INTO documents (content) VALUES ('Jump squats improve explosive strength.');
INSERT INTO documents (content) VALUES ('Incline bench press targets upper chest muscles.');
INSERT INTO documents (content) VALUES ('Decline bench press targets lower chest muscles.');
INSERT INTO documents (content) VALUES ('Cable crossover isolates the chest muscles.');
INSERT INTO documents (content) VALUES ('Seated row strengthens the middle back muscles.');
INSERT INTO documents (content) VALUES ('T-bar row targets the back and improves pulling strength.');
INSERT INTO documents (content) VALUES ('Reverse fly improves shoulder stability and posture.');
INSERT INTO documents (content) VALUES ('Front raise isolates the anterior deltoid.');
INSERT INTO documents (content) VALUES ('Lateral raise targets the side deltoids.');
INSERT INTO documents (content) VALUES ('Shrugs strengthen the trapezius muscles.');
INSERT INTO documents (content) VALUES ('Good mornings strengthen the hamstrings and lower back.');
INSERT INTO documents (content) VALUES ('Romanian deadlift targets the posterior chain.');
INSERT INTO documents (content) VALUES ('Goblet squat improves squat form and core stability.');
INSERT INTO documents (content) VALUES ('Bulgarian split squat strengthens legs individually.');
INSERT INTO documents (content) VALUES ('Hack squat targets quadriceps using a machine.');
INSERT INTO documents (content) VALUES ('Sled push improves strength and conditioning.');
INSERT INTO documents (content) VALUES ('Battle ropes improve cardio and upper body endurance.');
INSERT INTO documents (content) VALUES ('Ab wheel rollout strengthens the core muscles.');
INSERT INTO documents (content) VALUES ('Hanging leg raises target lower abs.');
INSERT INTO documents (content) VALUES ('Cable crunch strengthens abdominal muscles.');
INSERT INTO documents (content) VALUES ('Toe touches improve core flexibility.');
INSERT INTO documents (content) VALUES ('Flutter kicks strengthen the lower abdominal muscles.');
INSERT INTO documents (content) VALUES ('Bear crawl improves full body coordination.');
INSERT INTO documents (content) VALUES ('Crab walk strengthens arms and core.');
INSERT INTO documents (content) VALUES ('Medicine ball slams improve power and conditioning.');
INSERT INTO documents (content) VALUES ('Resistance band pull apart improves shoulder health.');
INSERT INTO documents (content) VALUES ('Resistance band squats improve leg strength.');
INSERT INTO documents (content) VALUES ('Resistance band rows strengthen the back muscles.');
INSERT INTO documents (content) VALUES ('Resistance band curls improve arm strength.');
INSERT INTO documents (content) VALUES ('Resistance band pushdowns target triceps.');
INSERT INTO documents (content) VALUES ('Resistance band lateral walks activate glutes.');
INSERT INTO documents (content) VALUES ('Close grip bench press targets the inner chest and triceps using a narrow grip on the barbell.');
INSERT INTO documents (content) VALUES ('Diamond push-ups increase triceps activation by placing hands close together.');
INSERT INTO documents (content) VALUES ('Chest dips target the lower chest and triceps using parallel bars.');
INSERT INTO documents (content) VALUES ('Machine chest press strengthens the chest using guided resistance.');
INSERT INTO documents (content) VALUES ('Pec deck fly isolates the chest muscles using a machine.');
INSERT INTO documents (content) VALUES ('Landmine press strengthens shoulders and chest using a barbell anchored to the floor.');
INSERT INTO documents (content) VALUES ('Push press builds explosive shoulder strength using leg drive.');
INSERT INTO documents (content) VALUES ('Z press improves shoulder stability while seated on the floor.');
INSERT INTO documents (content) VALUES ('Cable front raise isolates the front deltoids using a cable machine.');
INSERT INTO documents (content) VALUES ('Upright row targets shoulders and traps using a barbell or dumbbells.');
INSERT INTO documents (content) VALUES ('Chin-ups strengthen the back and biceps using a supinated grip.');
INSERT INTO documents (content) VALUES ('Inverted rows improve upper back strength using bodyweight under a bar.');
INSERT INTO documents (content) VALUES ('Single arm dumbbell row targets the lats and improves balance.');
INSERT INTO documents (content) VALUES ('Pendlay row builds explosive back strength from the floor.');
INSERT INTO documents (content) VALUES ('Meadows row isolates the lats using a landmine setup.');
INSERT INTO documents (content) VALUES ('Straight arm pulldown isolates the lats using a cable machine.');
INSERT INTO documents (content) VALUES ('Wide grip lat pulldown emphasizes upper lats.');
INSERT INTO documents (content) VALUES ('Close grip seated row targets the middle back.');
INSERT INTO documents (content) VALUES ('Renegade rows strengthen the core and back simultaneously.');
INSERT INTO documents (content) VALUES ('Resistance band face pulls improve shoulder stability.');
INSERT INTO documents (content) VALUES ('Barbell back squat builds overall leg strength.');
INSERT INTO documents (content) VALUES ('Front squat targets quadriceps and core stability.');
INSERT INTO documents (content) VALUES ('Sumo deadlift emphasizes inner thighs and glutes.');
INSERT INTO documents (content) VALUES ('Trap bar deadlift reduces lower back strain while building strength.');
INSERT INTO documents (content) VALUES ('Walking lunges improve unilateral leg strength and balance.');
INSERT INTO documents (content) VALUES ('Reverse lunges reduce knee stress while strengthening legs.');
INSERT INTO documents (content) VALUES ('Curtsey lunges target glutes and inner thighs.');
INSERT INTO documents (content) VALUES ('Smith machine squat provides guided lower body strength training.');
INSERT INTO documents (content) VALUES ('Leg press calf raises strengthen calves using a machine.');
INSERT INTO documents (content) VALUES ('Single leg Romanian deadlift improves balance and hamstring strength.');
INSERT INTO documents (content) VALUES ('Nordic hamstring curls strengthen hamstrings eccentrically.');
INSERT INTO documents (content) VALUES ('Glute kickbacks isolate glutes using cable or bodyweight.');
INSERT INTO documents (content) VALUES ('Cable pull-through targets the posterior chain.');
INSERT INTO documents (content) VALUES ('Step-downs improve knee stability and control.');
INSERT INTO documents (content) VALUES ('Broad jumps build explosive lower body power.');
INSERT INTO documents (content) VALUES ('Depth jumps improve reactive strength.');
INSERT INTO documents (content) VALUES ('Wall balls combine squat and overhead press for conditioning.');
INSERT INTO documents (content) VALUES ('Thrusters combine front squat and overhead press.');
INSERT INTO documents (content) VALUES ('Pistol squats improve single leg strength and mobility.');
INSERT INTO documents (content) VALUES ('Cossack squats increase hip mobility and leg strength.');
INSERT INTO documents (content) VALUES ('Sit-ups strengthen abdominal muscles through full range motion.');
INSERT INTO documents (content) VALUES ('V-ups improve core strength and coordination.');
INSERT INTO documents (content) VALUES ('Hollow body hold strengthens deep core muscles.');
INSERT INTO documents (content) VALUES ('Dead bug exercise improves core stability and coordination.');
INSERT INTO documents (content) VALUES ('Bird dog strengthens lower back and core stability.');
INSERT INTO documents (content) VALUES ('Standing cable rotations strengthen obliques dynamically.');
INSERT INTO documents (content) VALUES ('Woodchoppers improve rotational core power.');
INSERT INTO documents (content) VALUES ('Plank shoulder taps improve core stability and shoulder control.');
INSERT INTO documents (content) VALUES ('Weighted decline sit-ups increase abdominal resistance.');
INSERT INTO documents (content) VALUES ('Medicine ball Russian twists improve rotational strength.');
INSERT INTO documents (content) VALUES ('Sprint intervals improve speed and cardiovascular endurance.');
INSERT INTO documents (content) VALUES ('Treadmill incline walk increases lower body endurance.');
INSERT INTO documents (content) VALUES ('Rowing machine improves full body cardio conditioning.');
INSERT INTO documents (content) VALUES ('Cycling sprints build leg endurance and power.');
INSERT INTO documents (content) VALUES ('Stair climber improves cardiovascular fitness and leg endurance.');
INSERT INTO documents (content) VALUES ('Agility ladder drills improve coordination and speed.');
INSERT INTO documents (content) VALUES ('Shuttle runs improve acceleration and agility.');
INSERT INTO documents (content) VALUES ('Battle rope waves increase upper body endurance.');
INSERT INTO documents (content) VALUES ('Shadow boxing improves coordination and cardio fitness.');
INSERT INTO documents (content) VALUES ('Ski erg improves full body conditioning.');
INSERT INTO documents (content) VALUES ('Resistance band chest press strengthens chest with elastic resistance.');
INSERT INTO documents (content) VALUES ('Resistance band deadlifts strengthen posterior chain.');
INSERT INTO documents (content) VALUES ('Resistance band lateral raises target shoulders.');
INSERT INTO documents (content) VALUES ('Resistance band hip thrust activates glutes.');
INSERT INTO documents (content) VALUES ('Resistance band monster walks improve glute activation.');
INSERT INTO documents (content) VALUES ('Resistance band good mornings strengthen hamstrings.');
INSERT INTO documents (content) VALUES ('Resistance band seated rows target back muscles.');
INSERT INTO documents (content) VALUES ('Resistance band overhead triceps extension strengthens triceps.');
INSERT INTO documents (content) VALUES ('Resistance band hammer curls improve arm strength.');
INSERT INTO documents (content) VALUES ('Resistance band glute bridges activate glutes.');
INSERT INTO documents (content) VALUES ('Decline push-ups increase upper chest and shoulder activation by elevating the feet.');
INSERT INTO documents (content) VALUES ('Archer push-ups improve unilateral chest and arm strength.');
INSERT INTO documents (content) VALUES ('Spiderman push-ups engage the core and hip flexors during the movement.');
INSERT INTO documents (content) VALUES ('Clap push-ups build explosive upper body power.');
INSERT INTO documents (content) VALUES ('Pseudo planche push-ups strengthen shoulders and wrists.');
INSERT INTO documents (content) VALUES ('Ring push-ups improve chest activation and stability.');
INSERT INTO documents (content) VALUES ('Single arm push-ups develop unilateral strength and balance.');
INSERT INTO documents (content) VALUES ('Wall handstand push-ups build shoulder strength using bodyweight.');
INSERT INTO documents (content) VALUES ('Pike push-ups target shoulders with bodyweight resistance.');
INSERT INTO documents (content) VALUES ('Floor press strengthens chest and triceps with limited shoulder strain.');
INSERT INTO documents (content) VALUES ('Dumbbell bench press improves chest symmetry and stability.');
INSERT INTO documents (content) VALUES ('Resistance band chest fly increases constant tension on chest muscles.');
INSERT INTO documents (content) VALUES ('Guillotine press targets upper chest with a wide grip.');
INSERT INTO documents (content) VALUES ('Svend press isolates chest by pressing weight plates together.');
INSERT INTO documents (content) VALUES ('Isometric push-up hold improves muscular endurance.');
INSERT INTO documents (content) VALUES ('Chest squeeze press increases chest contraction using dumbbells.');
INSERT INTO documents (content) VALUES ('Alternating dumbbell press improves unilateral control.');
INSERT INTO documents (content) VALUES ('Plate front raises strengthen shoulders and grip.');
INSERT INTO documents (content) VALUES ('Cable reverse fly strengthens rear deltoids.');
INSERT INTO documents (content) VALUES ('Band pullovers activate lats and chest.');
INSERT INTO documents (content) VALUES ('Wide grip pull-ups emphasize upper back width.');
INSERT INTO documents (content) VALUES ('Commando pull-ups improve grip and arm strength.');
INSERT INTO documents (content) VALUES ('Assisted pull-ups help beginners build back strength.');
INSERT INTO documents (content) VALUES ('Scapular pull-ups improve shoulder control and stability.');
INSERT INTO documents (content) VALUES ('Rack pulls strengthen upper portion of deadlift movement.');
INSERT INTO documents (content) VALUES ('Deficit deadlifts increase range of motion and strength.');
INSERT INTO documents (content) VALUES ('Snatch grip deadlifts emphasize upper back engagement.');
INSERT INTO documents (content) VALUES ('Barbell shrugs build trapezius size and strength.');
INSERT INTO documents (content) VALUES ('Dumbbell shrugs improve trap symmetry.');
INSERT INTO documents (content) VALUES ('Cable rows with pause increase time under tension.');
INSERT INTO documents (content) VALUES ('Heel elevated squats emphasize quadriceps activation.');
INSERT INTO documents (content) VALUES ('Box squats improve squat depth control and power.');
INSERT INTO documents (content) VALUES ('Pause squats increase lower body strength and stability.');
INSERT INTO documents (content) VALUES ('Tempo squats improve muscle control and endurance.');
INSERT INTO documents (content) VALUES ('Jefferson squats improve hip mobility and leg strength.');
INSERT INTO documents (content) VALUES ('Zercher squats strengthen core and legs simultaneously.');
INSERT INTO documents (content) VALUES ('Sissy squats isolate quadriceps intensely.');
INSERT INTO documents (content) VALUES ('Resistance band jump squats increase explosive strength.');
INSERT INTO documents (content) VALUES ('Single leg box squats improve unilateral leg strength.');
INSERT INTO documents (content) VALUES ('Isometric wall squat hold builds quad endurance.');
INSERT INTO documents (content) VALUES ('Glute ham raises strengthen posterior chain muscles.');
INSERT INTO documents (content) VALUES ('Cable kickbacks isolate glutes with constant tension.');
INSERT INTO documents (content) VALUES ('Banded hip abductions activate glute medius.');
INSERT INTO documents (content) VALUES ('Banded hip adductions strengthen inner thighs.');
INSERT INTO documents (content) VALUES ('Standing calf raises build calf strength using bodyweight.');
INSERT INTO documents (content) VALUES ('Seated calf raises isolate soleus muscle.');
INSERT INTO documents (content) VALUES ('Donkey calf raises increase calf stretch and activation.');
INSERT INTO documents (content) VALUES ('Tibialis raises strengthen the front lower leg muscles.');
INSERT INTO documents (content) VALUES ('Ankle hops improve lower leg explosiveness.');
INSERT INTO documents (content) VALUES ('Broad stance squats target inner thighs.');
INSERT INTO documents (content) VALUES ('Dragon flags build advanced core strength.');
INSERT INTO documents (content) VALUES ('Cable woodchop rotations improve rotational power.');
INSERT INTO documents (content) VALUES ('Hanging windshield wipers strengthen obliques dynamically.');
INSERT INTO documents (content) VALUES ('Reverse crunches target lower abdominal muscles.');
INSERT INTO documents (content) VALUES ('Weighted planks increase core resistance.');
INSERT INTO documents (content) VALUES ('Side plank hip dips improve oblique endurance.');
INSERT INTO documents (content) VALUES ('Swiss ball crunches increase abdominal activation.');
INSERT INTO documents (content) VALUES ('Stability ball rollouts improve core control.');
INSERT INTO documents (content) VALUES ('Kneeling ab rollouts strengthen core progressively.');
INSERT INTO documents (content) VALUES ('Medicine ball sit-ups add resistance to ab training.');
INSERT INTO documents (content) VALUES ('Sled drags improve conditioning and leg strength.');
INSERT INTO documents (content) VALUES ('Hill sprints build explosive speed and power.');
INSERT INTO documents (content) VALUES ('Tempo runs improve aerobic capacity.');
INSERT INTO documents (content) VALUES ('Jump lunges improve leg explosiveness.');
INSERT INTO documents (content) VALUES ('Skater jumps increase lateral power and coordination.');
INSERT INTO documents (content) VALUES ('Box step overs improve agility and balance.');
INSERT INTO documents (content) VALUES ('Bear plank shoulder taps strengthen core stability.');
INSERT INTO documents (content) VALUES ('Crab toe touches improve coordination and core control.');
INSERT INTO documents (content) VALUES ('Battle rope slams increase upper body power.');
INSERT INTO documents (content) VALUES ('Rowing sprints build cardiovascular endurance quickly.');
INSERT INTO documents (content) VALUES ('Resistance band push-ups increase chest tension.');
INSERT INTO documents (content) VALUES ('Resistance band split squats improve leg strength.');
INSERT INTO documents (content) VALUES ('Resistance band face pulls strengthen rear deltoids.');
INSERT INTO documents (content) VALUES ('Resistance band overhead squats improve mobility and stability.');
INSERT INTO documents (content) VALUES ('Resistance band speed rows improve explosive pulling strength.');
INSERT INTO documents (content) VALUES ('Resistance band tricep kickbacks isolate triceps.');
INSERT INTO documents (content) VALUES ('Resistance band lateral lunges target glutes and inner thighs.');
INSERT INTO documents (content) VALUES ('Resistance band seated leg curls strengthen hamstrings.');
INSERT INTO documents (content) VALUES ('Resistance band reverse fly improves posture.');
INSERT INTO documents (content) VALUES ('Resistance band squat to press combines lower and upper body work.');
INSERT INTO documents (content) VALUES ('Around the world shoulder raises improve shoulder mobility and control using dumbbells.');
INSERT INTO documents (content) VALUES ('Incline push-ups reduce load while strengthening chest and triceps.');
INSERT INTO documents (content) VALUES ('Decline dumbbell fly increases upper chest activation on an incline bench.');
INSERT INTO documents (content) VALUES ('Cross body cable press targets chest with rotational movement.');
INSERT INTO documents (content) VALUES ('Standing landmine chest press improves unilateral pressing strength.');
INSERT INTO documents (content) VALUES ('Overhead carry strengthens shoulders and core stability while walking.');
INSERT INTO documents (content) VALUES ('Bottoms-up kettlebell press improves shoulder stability and grip strength.');
INSERT INTO documents (content) VALUES ('Kettlebell clean builds explosive hip and upper body power.');
INSERT INTO documents (content) VALUES ('Kettlebell snatch improves full body coordination and conditioning.');
INSERT INTO documents (content) VALUES ('Dumbbell pullover strengthens chest and lats simultaneously.');
INSERT INTO documents (content) VALUES ('Chest supported dumbbell row isolates back muscles with minimal lower back strain.');
INSERT INTO documents (content) VALUES ('Resistance band assisted dips help build tricep strength for beginners.');
INSERT INTO documents (content) VALUES ('Isometric chin-up hold improves pulling endurance.');
INSERT INTO documents (content) VALUES ('Mixed grip pull-ups increase grip variation strength.');
INSERT INTO documents (content) VALUES ('Reverse grip barbell row targets lower lats and biceps.');
INSERT INTO documents (content) VALUES ('Seal rows isolate upper back while lying face down on a bench.');
INSERT INTO documents (content) VALUES ('Incline dumbbell rows increase upper back activation.');
INSERT INTO documents (content) VALUES ('Cable lat prayers isolate the lats with straight arm movement.');
INSERT INTO documents (content) VALUES ('Scapular wall slides improve shoulder mobility and posture.');
INSERT INTO documents (content) VALUES ('Prone Y raises strengthen lower trapezius muscles.');
INSERT INTO documents (content) VALUES ('Box pistol squats assist single leg strength development.');
INSERT INTO documents (content) VALUES ('Elevated split squats increase range of motion for glutes.');
INSERT INTO documents (content) VALUES ('Banded lateral step walks activate glute medius muscles.');
INSERT INTO documents (content) VALUES ('Barbell hip thrust with pause increases glute tension.');
INSERT INTO documents (content) VALUES ('Single leg hip thrust improves unilateral glute strength.');
INSERT INTO documents (content) VALUES ('Reverse hyperextensions strengthen lower back and glutes.');
INSERT INTO documents (content) VALUES ('Kettlebell goblet lunges improve posture and balance.');
INSERT INTO documents (content) VALUES ('Lateral box jumps increase side to side explosiveness.');
INSERT INTO documents (content) VALUES ('Banded squat pulses improve glute endurance.');
INSERT INTO documents (content) VALUES ('Paused Romanian deadlifts increase hamstring tension.');
INSERT INTO documents (content) VALUES ('Cable glute abductions isolate outer hip muscles.');
INSERT INTO documents (content) VALUES ('Standing hamstring curls with band strengthen knee flexion.');
INSERT INTO documents (content) VALUES ('Wall supported handstand hold improves shoulder endurance.');
INSERT INTO documents (content) VALUES ('Hanging knee tucks strengthen lower abdominal muscles.');
INSERT INTO documents (content) VALUES ('Seated medicine ball rotations improve controlled core strength.');
INSERT INTO documents (content) VALUES ('Cable anti-rotation press improves core stability.');
INSERT INTO documents (content) VALUES ('Stir the pot plank increases dynamic core engagement.');
INSERT INTO documents (content) VALUES ('Barbell rollout strengthens anterior core muscles.');
INSERT INTO documents (content) VALUES ('Toe to bar strengthens advanced core control.');
INSERT INTO documents (content) VALUES ('Standing oblique crunch with cable isolates side abs.');
INSERT INTO documents (content) VALUES ('Assault bike intervals improve high intensity conditioning.');
INSERT INTO documents (content) VALUES ('Farmer carry with trap bar increases total body strength.');
INSERT INTO documents (content) VALUES ('Weighted sled marches build lower body endurance.');
INSERT INTO documents (content) VALUES ('Bounding drills improve sprint mechanics and explosiveness.');
INSERT INTO documents (content) VALUES ('Carioca drills improve hip mobility and coordination.');
INSERT INTO documents (content) VALUES ('Lateral shuffle drills increase agility.');
INSERT INTO documents (content) VALUES ('Backward sled drags strengthen quadriceps safely.');
INSERT INTO documents (content) VALUES ('Box depth drops improve landing mechanics.');
INSERT INTO documents (content) VALUES ('Power skips increase sprint explosiveness.');
INSERT INTO documents (content) VALUES ('Med ball chest pass builds explosive pushing power.');
INSERT INTO documents (content) VALUES ('Resistance band pullovers strengthen lats with elastic resistance.');
INSERT INTO documents (content) VALUES ('Resistance band step-ups improve lower body control.');
INSERT INTO documents (content) VALUES ('Resistance band front squats improve posture and core strength.');
INSERT INTO documents (content) VALUES ('Resistance band single arm rows improve unilateral pulling.');
INSERT INTO documents (content) VALUES ('Resistance band overhead carries improve shoulder stability.');
INSERT INTO documents (content) VALUES ('Resistance band hamstring kickbacks isolate glutes.');
INSERT INTO documents (content) VALUES ('Resistance band ankle dorsiflexion strengthens shin muscles.');
INSERT INTO documents (content) VALUES ('Resistance band lateral shoulder walks improve rotator cuff strength.');
INSERT INTO documents (content) VALUES ('Resistance band rotational punches improve core power.');
INSERT INTO documents (content) VALUES ('Resistance band split stance presses improve stability.');
